### ISSUE TITLE
VAE Encode (AI Template) Shifts Image Down and to the Right.

### ISSUE THREAD

**Issue by IdiotSandwichTheThird** [hlky/AIT#4]
Example:
https://i.imgur.com/8QTd3cH.png
Simple Setup to reproduce:
[Example.txt](https://github.com/hlky/AIT/files/11878426/Example.txt)

**Comment by hlky** [comment]
Thanks for bringing this up, I was aware of the issue but hadn't got round to fixing it yet.

I've made some progress.

![image](https://github.com/hlky/AIT/assets/106811348/12dd9653-2449-4a2c-b9bc-53b36a2d5b0f)

It's better but not perfect yet.

I'm going to delay uploading VAE modules at different batch sizes until this issue is resolved.

**Comment by hlky** [comment]
Fixed. Modules are compiling now.

![image](https://github.com/hlky/AIT/assets/106811348/46344033-0451-4343-bd18-e82377e02a26)

**Comment by IdiotSandwichTheThird** [comment]
Thanks for the quick fix!

**Comment by hlky** [comment]
Fixed VAE encode modules, and batch VAE decode/encode modules for Windows SM75 and SM80 are available on huggingface.

**Comment by IdiotSandwichTheThird** [comment]
I git pulled, but the issue still shows up for me with the above setup. Do I need to update to the latest modules?
https://i.imgur.com/E6xYdyM.png

**Comment by hlky** [comment]
Of course.
